# Generated by Django 4.2.30 on 2026-09-25 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_alter_duplicatecandidate_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SealPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('package_no', models.CharField(editable=False, max_length=32, unique=True, verbose_name='封存包编号')),
                ('subject_kind', models.CharField(choices=[('event', '事件封存'), ('penalty', '处罚封存')], max_length=16, verbose_name='封存对象类型')),
                ('package_kind', models.CharField(choices=[('initial', '首次封存'), ('supplement', '补充包'), ('replacement', '替代包')], default='initial', max_length=16, verbose_name='包类型')),
                ('status', models.CharField(choices=[('pending', '待封存'), ('sealed', '已封存'), ('supplemented', '已补充（历史包）'), ('verification_failed', '校验失败'), ('superceded', '已替代（历史包）')], db_index=True, default='pending', max_length=24, verbose_name='状态')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否为当前活动包')),
                ('relation_note', models.CharField(blank=True, default='', max_length=512, verbose_name='补充/替代说明')),
                ('client_token', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='客户端幂等键')),
                ('manifest', models.JSONField(blank=True, editable=False, null=True, verbose_name='封存清单')),
                ('manifest_digest', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='清单摘要(sha256)')),
                ('content_fingerprint', models.CharField(blank=True, default='', help_text='重复封存时若指纹相同则直接返回既有活动包，不产生第二个活动包', max_length=64, verbose_name='内容指纹(不含文件摘要)')),
                ('sealed_at', models.DateTimeField(blank=True, null=True, verbose_name='封存时间')),
                ('sealed_by', models.CharField(blank=True, default='', max_length=64, verbose_name='封存操作人')),
                ('legacy_migrated', models.BooleanField(default=False, verbose_name='历史数据迁移生成')),
                ('missing_files', models.BooleanField(default=False, verbose_name='封存时即有文件缺失')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seal_packages', to='assessment.problemevent', verbose_name='问题事件')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='assessment.sealpackage', verbose_name='上一版本包')),
                ('penalty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seal_packages', to='assessment.penaltyunit', verbose_name='处罚单元')),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaced_by_set', to='assessment.sealpackage', verbose_name='被替代的包')),
            ],
            options={
                'verbose_name': '证据封存包',
                'verbose_name_plural': '证据封存包',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SealVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('online', '在线校验'), ('offline', '离线校验'), ('export', '导出校验')], max_length=16, verbose_name='校验来源')),
                ('result', models.CharField(choices=[('valid', '校验通过'), ('invalid', '校验失败')], max_length=16, verbose_name='校验结果')),
                ('manifest_ok', models.BooleanField(default=False, verbose_name='清单摘要一致')),
                ('checked_files', models.PositiveIntegerField(default=0, verbose_name='已校验文件数')),
                ('mismatch_files', models.JSONField(blank=True, default=list, verbose_name='摘要不符文件')),
                ('missing_files', models.JSONField(blank=True, default=list, verbose_name='缺失文件')),
                ('extra_files', models.JSONField(blank=True, default=list, verbose_name='包外多余文件')),
                ('detail', models.CharField(blank=True, default='', max_length=512, verbose_name='说明')),
                ('actor', models.CharField(blank=True, default='', max_length=64, verbose_name='校验人/任务')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='校验时间')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifications', to='assessment.sealpackage', verbose_name='封存包')),
            ],
            options={
                'verbose_name': '封存校验记录',
                'verbose_name_plural': '封存校验记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SealExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_token', models.CharField(max_length=64, verbose_name='客户端幂等键')),
                ('status', models.CharField(choices=[('pending', '待导出'), ('building', '构建中'), ('completed', '已完成'), ('failed', '失败')], db_index=True, default='pending', max_length=16, verbose_name='状态')),
                ('bundle_path', models.CharField(blank=True, default='', max_length=512, verbose_name='导出包路径')),
                ('bundle_digest', models.CharField(blank=True, default='', max_length=64, verbose_name='导出包摘要(sha256)')),
                ('size_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='导出包大小')),
                ('total_files', models.PositiveIntegerField(default=0, verbose_name='待导出文件数')),
                ('done_files', models.PositiveIntegerField(default=0, verbose_name='已导出文件数')),
                ('cursor', models.CharField(blank=True, default='', max_length=512, verbose_name='续作游标(最后写入的 rel_path)')),
                ('error', models.CharField(blank=True, default='', max_length=512, verbose_name='失败原因')),
                ('created_by', models.CharField(blank=True, default='', max_length=64, verbose_name='请求人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_jobs', to='assessment.sealpackage', verbose_name='封存包')),
            ],
            options={
                'verbose_name': '封存导出任务',
                'verbose_name_plural': '封存导出任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SealedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('evidence', '证据照片'), ('rectification', '整改照片'), ('attachment', '外部文件')], max_length=16, verbose_name='文件角色')),
                ('rel_path', models.CharField(max_length=512, verbose_name='包内相对路径')),
                ('storage_path', models.CharField(blank=True, default='', max_length=512, verbose_name='存储路径')),
                ('filename', models.CharField(max_length=256, verbose_name='文件名')),
                ('content_type', models.CharField(blank=True, default='', max_length=64, verbose_name='内容类型')),
                ('size_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='文件大小(字节)')),
                ('sha256', models.CharField(blank=True, default='', max_length=64, verbose_name='封存时文件摘要(sha256)')),
                ('missing_at_seal', models.BooleanField(default=False, verbose_name='封存时文件缺失')),
                ('phash', models.CharField(blank=True, default='', max_length=64, verbose_name='感知哈希(hex)')),
                ('captured_at', models.DateTimeField(blank=True, null=True, verbose_name='拍摄时间')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='纬度')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='assessment.sealpackage', verbose_name='封存包')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sealed_files', to='assessment.evidencephoto', verbose_name='证据照片')),
            ],
            options={
                'verbose_name': '封存清单文件',
                'verbose_name_plural': '封存清单文件',
                'ordering': ['rel_path'],
            },
        ),
        migrations.AddIndex(
            model_name='sealpackage',
            index=models.Index(fields=['penalty', 'package_kind'], name='assessment__penalty_5aa581_idx'),
        ),
        migrations.AddIndex(
            model_name='sealpackage',
            index=models.Index(fields=['status', 'is_active'], name='assessment__status_3f298b_idx'),
        ),
        migrations.AddConstraint(
            model_name='sealpackage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('penalty',), name='uniq_active_seal_per_penalty'),
        ),
        migrations.AddConstraint(
            model_name='sealpackage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('event',), name='uniq_active_seal_per_event'),
        ),
        migrations.AddConstraint(
            model_name='sealpackage',
            constraint=models.UniqueConstraint(condition=models.Q(('client_token', ''), _negated=True), fields=('penalty', 'client_token'), name='uniq_seal_penalty_token'),
        ),
        migrations.AddConstraint(
            model_name='sealexportjob',
            constraint=models.UniqueConstraint(fields=('package', 'client_token'), name='uniq_export_token'),
        ),
        migrations.AddIndex(
            model_name='sealedfile',
            index=models.Index(fields=['photo'], name='assessment__photo_i_1a6a7f_idx'),
        ),
        migrations.AddIndex(
            model_name='sealedfile',
            index=models.Index(fields=['sha256'], name='assessment__sha256_14f5f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='sealedfile',
            constraint=models.UniqueConstraint(fields=('package', 'rel_path'), name='uniq_sealed_file_path'),
        ),
    ]
