# Generated by Django 4.2.30 on 2026-09-25 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_alter_duplicatecandidate_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidencePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('package_no', models.CharField(editable=False, max_length=32, unique=True, verbose_name='封存包编号')),
                ('kind', models.CharField(choices=[('original', '原始封存'), ('supplement', '补充包'), ('replacement', '替代包')], default='original', max_length=16, verbose_name='封存类型')),
                ('status', models.CharField(choices=[('pending', '待封存'), ('sealed', '已封存'), ('superseded', '已补充/已替代'), ('verify_failed', '校验失败')], default='pending', max_length=16, verbose_name='状态')),
                ('manifest', models.JSONField(verbose_name='不可变清单（封存后不再修改）')),
                ('manifest_hash', models.CharField(editable=False, max_length=64, verbose_name='清单SHA-256')),
                ('sealed_at', models.DateTimeField(blank=True, null=True, verbose_name='封存时间(注入时钟)')),
                ('sealed_by', models.CharField(blank=True, default='', max_length=64, verbose_name='封存人')),
                ('note', models.CharField(blank=True, max_length=512, verbose_name='封存说明')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='最近校验时间')),
                ('verify_report', models.JSONField(blank=True, null=True, verbose_name='最近校验报告')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='assessment.evidencepackage', verbose_name='被补充/替代的封存包')),
                ('penalty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='assessment.penaltyunit', verbose_name='处罚单元')),
                ('sealed_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sealed_by_packages', to='assessment.penaltyversion', verbose_name='封存时的当前处罚版本')),
            ],
            options={
                'verbose_name': '证据封存包',
                'verbose_name_plural': '证据封存包',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['penalty', 'status'], name='assessment__penalty_960358_idx'), models.Index(fields=['status', 'kind'], name='assessment__status_816492_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='evidencepackage',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'sealed'])), fields=('penalty',), name='uniq_active_evidence_package'),
        ),
    ]
